version: '2'
services:
    soclejava-app:
        image: soclejava
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://soclejava-mysql:3306/soclejava?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    soclejava-mysql:
        extends:
            file: mysql.yml
            service: soclejava-mysql
